name: mermaid

on:
  workflow_call:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Check for shared mermaid graphs
        id: check
        run: |
          find . -type f -name "*.md" -print0 | xargs -L 1 awk '/"shared": ?true/,/```$/' *.* >> /tmp/${{ github.event.repository.name }}.mmd
          cat /tmp/${{ github.event.repository.name }}.mmd
