name: mermaid

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Check for shared mermaid graphs
        id: check
        run: |
          find . -type f -name "*.md" -print0 | \
            xargs -L 1 awk '/%%.*"shared": ?true/,/```$/' \
            > /tmp/${{ github.event.repository.name }}.mmd
          cat /tmp/${{ github.event.repository.name }}.mmd
          if [ -s /tmp/${{ github.event.repository.name }} ];then
            has_graphs=1
          else
            has_graphs=0
            echo "### No mermaid graphs detected in repo :disappointed:" >> $GITHUB_STEP_SUMMARY
          fi
          echo "HAS_GRAPHS={has_graphs}" >> $GITHUB_OUTPUT

      - name: Checkout Documentation repo
        if: ${{ steps.check.outputs.HAS_GRAPHS }} == 1
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          token: ${{ inputs.token }}

      - name: Copy file to graph folder
        if: ${{ steps.check.outputs.HAS_GRAPHS }} == 1
        run: |
          cp /tmp/${{ github.event.repository.name }}.mmd graphs/

      - name: Diff check
        if: ${{ steps.check.outputs.HAS_GRAPHS }} == 1
        id: diff
        run: |
          if [[ `git status --porcelain` ]]; then
            changes=1
          else
            changes=0
            echo "### No mermaid graph changes detected :hurtrealbad:" >> $GITHUB_STEP_SUMMARY
          fi
          echo "CHANGES={changes}" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: ${{ steps.diff.outputs.CHANGES }} == 1
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add graphs
          git commit -m "automated: updating ${{github.event.repository.name}} graph from repository"
          git push origin ${{ inputs.branch }}
          echo "### Sending updated mermaid graph changes to central Documentation repo :rocket:" >> $GITHUB_STEP_SUMMARY
