name: mermaid

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Check for shared mermaid graphs
        run: |
          find . -type f -name "*.md" -print0 | xargs -L 1 awk '/"shared": ?true/,/```$/' | sed 's/```//g' > /tmp/${{ github.event.repository.name }}.mmd
          cat /tmp/${{ github.event.repository.name }}.mmd

      - name: Checkout Documentation repo
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          path: 'Documentation'

      - name: Test
        run: |
          ls -la $GITHUB_WORKSPACE
        
